default: &default
  adapter: postgresql
  encoding: unicode
  pool: 16
  username: <%= Rails.application.credentials.username %>
  password: <%= Rails.application.credentials.password %>
  host: localhost

development:
  <<: *default
  database: <%= Rails.application.credentials.db_name %>
test:
  <<: *default
  database: content_test
production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
