default: &default
  adapter: postgresql
  encoding: unicode
  pool: 16
  username: beautibly
  password: password
  host: localhost

development:
  <<: *default
  database: content_app
test:
  <<: *default
  database: content_test
production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
